# Generated by Django 4.0.1 on 2022-02-07 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/instruments/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(max_length=256, upload_to='icons/links/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/projects/')),
                ('month_created', models.DateField()),
                ('involvement', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=32)),
                ('designation', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('PERSONAL', 'Personal'), ('STUDY', 'Study')], max_length=32)),
                ('short_description', models.TextField(max_length=512)),
                ('overview_video', models.FileField(blank=True, max_length=256, null=True, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('overview_video_preview', models.ImageField(blank=True, max_length=256, null=True, upload_to='images/overview_previews/')),
                ('is_actual', models.BooleanField(default=False)),
                ('is_shown', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-month_created',),
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/technologies/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=256)),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.linktype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.instrument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DESCRIPTION', 'Description'), ('FEATURES', 'Features'), ('CONTRIBUTION', 'Contribution')], max_length=64)),
                ('text', models.TextField(max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
