# Generated by Django 4.0.1 on 2022-01-22 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/instruments/')),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(max_length=256, upload_to='icons/links/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/projects/')),
                ('date_created', models.DateField()),
                ('involvement', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=32)),
                ('designation', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('PERSONAL', 'Personal'), ('STUDY', 'Study')], max_length=32)),
                ('overview_video', models.FileField(blank=True, max_length=256, null=True, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('is_actual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(max_length=256, upload_to='icons/technologies/')),
                ('type', models.CharField(choices=[('BACKEND', 'backend'), ('DB', 'DB'), ('FRONTEND', 'frontend'), ('DESIGN', 'design'), ('OTHER', 'other')], max_length=32)),
                ('is_shown_in_resume', models.BooleanField(default=False)),
                ('priority_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologySubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_substitute_obj_1', to='projects.technology')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_substitute_obj_2', to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_pair_obj_1', to='projects.technology')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_pair_obj_2', to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=256)),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.linktype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.instrument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
