# Generated by Django 4.0.1 on 2022-02-18 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='overview_video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mov', 'mp4'])]),
        ),
    ]
