# Generated by Django 4.0.1 on 2022-01-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_technology_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologysubstitute',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='technologysubstitute',
            name='substitute',
        ),
        migrations.AddField(
            model_name='technology',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_pair', to='projects.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_substitute', to='projects.technology'),
        ),
        migrations.DeleteModel(
            name='TechnologyPair',
        ),
        migrations.DeleteModel(
            name='TechnologySubstitute',
        ),
    ]
