# Generated by Django 4.0.1 on 2022-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_overview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticle',
            name='title',
            field=models.CharField(choices=[('DESCRIPTION', 'Description'), ('FEATURES', 'Features'), ('MY CONTRIBUTION', 'My contribution')], max_length=64),
        ),
    ]
