# Generated by Django 4.0.1 on 2022-01-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_technologysubstitute_obj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_shown_in_resume',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='priority_number',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='substitute',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='type',
        ),
    ]
