# Generated by Django 4.0.1 on 2022-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='month_created',
        ),
    ]
