# Generated by Django 4.0.1 on 2022-01-23 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_date_created_project_month_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOverviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=256, null=True, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='overview_video',
        ),
    ]
