# Generated by Django 4.0.1 on 2022-01-23 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectoverviewvideo_remove_project_overview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectoverviewvideo'),
        ),
        migrations.AlterField(
            model_name='projectoverviewvideo',
            name='video',
            field=models.FileField(max_length=256, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
