# Generated by Django 4.0.1 on 2022-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_overview_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
