# Generated by Django 4.0.1 on 2022-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='projectarticle',
            name='text',
            field=models.TextField(max_length=2048),
        ),
    ]
