# Generated by Django 4.0.1 on 2022-01-23 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='overview_video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='videos/overviews/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
        migrations.DeleteModel(
            name='ProjectOverviewVideo',
        ),
    ]
