# Generated by Django 4.0.1 on 2022-01-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_overview_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('name',)},
        ),
    ]
