# Generated by Django 4.0.1 on 2022-01-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_instrument_options_alter_technology_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-month_created',)},
        ),
    ]
