# Generated by Django 4.0.1 on 2022-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticle',
            name='title',
            field=models.CharField(choices=[('DESCRIPTION', 'Description'), ('FEATURES', 'Features'), ('CONTRIBUTION', 'Contribution')], max_length=64),
        ),
    ]
