# Generated by Django 4.0.1 on 2022-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectarticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_video_preview',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/overview_previews/'),
        ),
    ]
