# Generated by Django 4.0.1 on 2022-01-22 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(max_length=256, upload_to='icons/contact_links/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('link', models.URLField(max_length=256)),
                ('priority_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=64)),
                ('location', models.CharField(default='Los Santos, USA', max_length=64)),
                ('portrait', models.ImageField(blank=True, max_length=256, null=True, upload_to='images/portraits/')),
                ('resume_file', models.FileField(blank=True, max_length=256, null=True, upload_to='files/resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineElementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(max_length=256, upload_to='images/timeline_attachments/')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.timelineelement')),
            ],
        ),
    ]
