# Generated by Django 4.0.1 on 2022-02-07 13:06

import apps.about_me.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(max_length=256, upload_to='icons/contact_links/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('link', models.CharField(max_length=256, validators=[apps.about_me.validators.validate_contact_link])),
                ('priority_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority_number',),
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('location', models.CharField(default='', max_length=64)),
                ('portrait', models.ImageField(blank=True, max_length=256, null=True, upload_to='images/portraits/')),
                ('resume_file', models.FileField(blank=True, max_length=256, null=True, upload_to='files/resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('BACKEND', 'backend'), ('DB', 'DB'), ('FRONTEND', 'frontend'), ('DESIGN', 'design'), ('OTHER', 'other')], max_length=32, unique=True)),
                ('priority_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority_number',),
            },
        ),
        migrations.CreateModel(
            name='TimelineElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(max_length=1024)),
            ],
            options={
                'ordering': ('-start_year', '-end_year'),
            },
        ),
        migrations.CreateModel(
            name='TimelineElementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(max_length=256, upload_to='images/timeline_attachments/')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.timelineelement')),
            ],
        ),
    ]
