# Generated by Django 4.0.1 on 2022-01-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_contactlink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('BACKEND', 'backend'), ('DB', 'DB'), ('FRONTEND', 'frontend'), ('DESIGN', 'design'), ('OTHER', 'other')], max_length=32)),
                ('priority_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority_number',),
            },
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ('-priority_number',)},
        ),
    ]
