# Generated by Django 4.0.1 on 2022-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_technologysubstitute_technologypair'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('BACKEND', 'backend'), ('DB', 'DB'), ('FRONTEND', 'frontend'), ('DESIGN', 'design'), ('OTHER', 'other')], max_length=32, unique=True)),
                ('priority_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority_number',),
            },
        ),
        migrations.RemoveField(
            model_name='technologypair',
            name='obj_1',
        ),
        migrations.RemoveField(
            model_name='technologypair',
            name='obj_2',
        ),
        migrations.RemoveField(
            model_name='technologysubstitute',
            name='obj_1',
        ),
        migrations.RemoveField(
            model_name='technologysubstitute',
            name='obj_2',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='TechnologyPair',
        ),
        migrations.DeleteModel(
            name='TechnologySubstitute',
        ),
    ]
