# Generated by Django 4.0.1 on 2022-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_technologyblock_remove_technologypair_obj_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineelement',
            options={'ordering': ('-start_year', '-end_year')},
        ),
        migrations.RenameField(
            model_name='timelineelement',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='timelineelement',
            old_name='start_date',
            new_name='start_year',
        ),
    ]
