# Generated by Django 4.0.1 on 2022-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_alter_timelineelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
