# Generated by Django 4.0.1 on 2022-02-05 16:20

import apps.about_me.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_alter_maininfo_location_alter_maininfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlink',
            name='link',
            field=models.CharField(max_length=256, validators=[apps.about_me.validators.validate_contact_link]),
        ),
    ]
